language: bash

addons:
  apt:
    packages:
    - build-essential
before_install:
- export LOCAL="$(mktemp --directory --tmpdir=${TMPDIR:/tmp} local.bin.XXXXXX)"
- curl -L http://downloads.sourceforge.net/zsh/zsh-5.0.7.tar.gz | tar zx
- cd zsh-5.0.7
- ./configure --prefix=$LOCAL
- make
- make install
- cd -
- export PATH="$LOCAL/bin:$PATH"
- zsh --version

before_script:
    - git clone https://github.com/sstephenson/bats.git
    - cd bats
    - ./install.sh /usr/local
    - cd -

script:
    - bats tests.bats
