language: bash

addons:
  apt:
    packages:
    - build-essential
before_install:
- sudo add-apt-repository ppa:duggan/bats --yes
- sudo apt-get update -qq
- sudo apt-get install -qq bats
- sudo apt-get upgrade zsh

script:
    - bats tests.bats
