# sudo: false
language: bash

addons:
    apt:
        # sources:
        #     -
        packages:
            - build-essential
before_install:
    # # THIS MAY COME IN HANDY IF WE MIGRATE FROM LEGACY TO CONTAINER-BASED INFRASTRUCTURE (TRAVIS CI)
    #
    # - export LOCAL="$(mktemp --directory --tmpdir=${TMPDIR:/tmp} local.bin.XXXXXX)"
    # - curl -L http://downloads.sourceforge.net/zsh/zsh-5.0.7.tar.gz | tar zx
    # - cd zsh-5.0.7
    # - ./configure --prefix=$LOCAL
    # - make
    # - make install
    # - cd -
    # - export PATH="$LOCAL/bin:$PATH"
    # - which zsh
    # - zsh --version
    #
    - sudo add-apt-repository ppa:duggan/bats --yes
    - sudo apt-get update -qq
    - sudo apt-get install -qq bats
    - sudo apt-get install -qq zsh

script:
    - bats tests/
    # - bash test_prm.sh
    # - zsh -o shwordsplit -- test_prm.sh
    # - bash shunit2_test.sh
