sudo: false
language: bash

addons:
    apt:
        # sources:
        #     -
        packages:
            - build-essential
            - zsh

cache:
    directories:
        - $HOME/bats

before_install:
    # - export LOCAL="$(mktemp --directory --tmpdir=${TMPDIR:/tmp} local.bin.XXXXXX)"
    # - curl -L http://downloads.sourceforge.net/zsh/zsh-5.0.7.tar.gz | tar zx
    # - cd zsh-5.0.7
    # - ./configure --prefix=$LOCAL
    # - make
    # - make install
    # - cd -
    # - export PATH="$LOCAL/bin:$PATH"
    # - which zsh
    # - zsh --version

before_script:
    - git clone https://github.com/sstephenson/bats.git
    #- cd bats
    #- ./install.sh /usr/local
    - export PATH=$PATH:$PWD/bats/bin/

script:
    #- bats tests/
    - bash ./tests/run-tests.sh
